source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Turnstile_Example', :exclusive => true do
  pod "Turnstile", :path => "../"
end

target 'Turnstile_Tests', :exclusive => true do
  pod "Turnstile", :path => "../"

  
end
